baseURL = "https://gavlegoat.github.io/"
canonifyURLs = true
languagecode = "en"
author = "Greg Anderson"
title = "Greg Anderson"
theme = "hugo-coder"
defaultcontentlanguage = "en"
paginate = 20

[params]
    author = "Greg Anderson"
    description = "Greg Anderson personal site"
    info = "PhD Student at UT Austin"
    avatarurl = "img/me.jpg"
    hidefooter = true
    hidecredits = false
    hidecopyright = false
    rtl = false
    colorscheme = "auto"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/gavlegoat/"

[[params.social]]
    name = "Email"
    icon = "fa fa-envelope"
    weight = 2
    url = "mailto:ganderso@cs.utexas.edu"

[[menu.main]]
    name = "Publications"
    weight = 200
    identifier = "publications"
    url = "/publications/"

[[menu.main]]
    name = "About"
    weight = 100
    identifier = "about"
    url = "/about/"

[[menu.main]]
    name = "Research"
    weight = 150
    identifier = "research"
    url = "/research/"
